/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("Hello world.", classUnderTest.getGreeting(), "app should have a greeting");
    }
}
